/*****************************************************************************************
 * purpose   :  By user input it will take test case and generate numbers of nodes generated by current node
 * @file    :    binarySearch.js
 * @overview:  it will generating number of nodes generated by test cases
 * @author  : surendra 
 * @version : 1.0
 * @since   : 04/01/2019 
 ***************************************************************************/
var access = require('../Datastructures/utilityForDataStructures/binarySearch');
//accessing binarysearch class through require keyword 
function binarysearch()// method for binarySearchTree
{
    access.binarySearchTree(); // accessing binarysearchtree  from binary search 
}
binarysearch();